https://jakevdp.github.io/PythonDataScienceHandbook/02.08-sorting.html

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
def selection_sort(x):
    for i in range(len(x)):
        swap=i+np.argmin(x[i:])
        (x[i],x[swap])=(x[swap],x[i])
    return x

In [3]:
x=np.array([1,2,3,4,5,0])

In [4]:
selection_sort(x)

array([0, 1, 2, 3, 4, 5])

In [5]:
def bogosort(x):
    while np.any(x[:1]>x[1:]):
        np.random.shuffle(x)
    return x

In [6]:
bogosort(x)

array([0, 1, 2, 3, 4, 5])

In [7]:
x=np.array([2,1,4,3,5])
x.sort()

In [8]:
x

array([1, 2, 3, 4, 5])

In [12]:
%timeit x.sort()

537 ns ± 22.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [13]:
%timeit np.sort(x)

3.4 µs ± 38.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
np.argsort(x)

array([0, 1, 2, 3, 4], dtype=int64)

In [20]:
i=np.array([2,3,1,0])
z=np.argsort(i)
i[2]

1

In [21]:
for a in range(len(z)):
    print(i[z[a]])

0
1
2
3


In [22]:
i[z]

array([0, 1, 2, 3])