warm up

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
r1= pd.Series(np.random.rand(10))

In [3]:
r2= pd.Series(np.random.rand(10))

In [4]:
dataframe = pd.DataFrame({'a':r2,'b':r1})

In [5]:
dataframe

a         b
0  0.369607  0.672519
1  0.359479  0.743413
2  0.613675  0.080621
3  0.850072  0.354777
4  0.526214  0.703327
5  0.001014  0.626434
6  0.179783  0.012771
7  0.642876  0.404236
8  0.378042  0.313215
9  0.389677  0.400749

In [6]:
dataframe.T

0         1         2         3         4         5         6  \
a  0.369607  0.359479  0.613675  0.850072  0.526214  0.001014  0.179783   
b  0.672519  0.743413  0.080621  0.354777  0.703327  0.626434  0.012771   

          7         8         9  
a  0.642876  0.378042  0.389677  
b  0.404236  0.313215  0.400749

In [7]:
dataframe.values

array([[ 0.36960679,  0.67251892],
       [ 0.35947877,  0.74341256],
       [ 0.6136748 ,  0.08062144],
       [ 0.85007166,  0.354777  ],
       [ 0.52621417,  0.70332734],
       [ 0.00101392,  0.62643415],
       [ 0.17978314,  0.01277136],
       [ 0.64287583,  0.4042362 ],
       [ 0.3780417 ,  0.31321512],
       [ 0.38967716,  0.4007493 ]])

In [8]:
dataframe['a']

0    0.369607
1    0.359479
2    0.613675
3    0.850072
4    0.526214
5    0.001014
6    0.179783
7    0.642876
8    0.378042
9    0.389677
Name: a, dtype: float64

In [9]:
dataframe.iloc[:3,:2]

a         b
0  0.369607  0.672519
1  0.359479  0.743413
2  0.613675  0.080621

In [10]:
dataframe.iloc[1]

a    0.359479
b    0.743413
Name: 1, dtype: float64

In [11]:
dataframe.loc[dataframe.a>.5]

a         b
2  0.613675  0.080621
3  0.850072  0.354777
4  0.526214  0.703327
7  0.642876  0.404236

In [12]:
dataframe[['a','b']]

a         b
0  0.369607  0.672519
1  0.359479  0.743413
2  0.613675  0.080621
3  0.850072  0.354777
4  0.526214  0.703327
5  0.001014  0.626434
6  0.179783  0.012771
7  0.642876  0.404236
8  0.378042  0.313215
9  0.389677  0.400749

In [13]:
rng = np.random.RandomState(23)
ser = pd.Series(rng.randint(0,10,4))
ser

0    3
1    6
2    8
3    9
dtype: int32

In [14]:
df=pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A','B','C','D'])

In [15]:
df

A  B  C  D
0  6  8  7  9
1  3  6  1  2
2  5  5  0  5

In [16]:
np.exp(df)

A            B            C            D
0  403.428793  2980.957987  1096.633158  8103.083928
1   20.085537   403.428793     2.718282     7.389056
2  148.413159   148.413159     1.000000   148.413159

In [17]:
np.sin(df*np.pi/4)

A             B         C         D
0 -1.000000 -2.449294e-16 -0.707107  0.707107
1  0.707107 -1.000000e+00  0.707107  1.000000
2 -0.707107 -7.071068e-01  0.000000 -0.707107

In [18]:
area = pd.Series({'alaska':123456,'texas':234567,'california':2354123},name = 'area')

In [19]:
area

alaska         123456
california    2354123
texas          234567
Name: area, dtype: int64

In [20]:
population = pd.Series({'california':235443252,'texas':234567891,'alaska':235234324})

In [21]:
population

alaska        235234324
california    235443252
texas         234567891
dtype: int64

In [22]:
population /area

alaska        1905.410219
california     100.013148
texas         1000.003798
dtype: float64

In [23]:
area.index | population.index

Index(['alaska', 'california', 'texas'], dtype='object')

In [24]:
A=pd.Series([2,4,6],index=[0,1,2])
B=pd.Series([1,3,5],index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [25]:
A.add(B,fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [26]:
A=pd.DataFrame(rng.randint(0,20,(2,2)),columns = list('ab'))
A

a   b
0  16   9
1  15  19

In [27]:
b=pd.DataFrame(rng.randint(0,10,(3,3)),columns = list('abc'))

In [28]:
b

a  b  c
0  1  7  4
1  1  1  4
2  6  7  3

In [29]:
A.add(b,fill_value=0)

a     b    c
0  17.0  16.0  4.0
1  16.0  20.0  4.0
2   6.0   7.0  3.0

In [30]:
A+b

a     b   c
0  17.0  16.0 NaN
1  16.0  20.0 NaN
2   NaN   NaN NaN

In [31]:
A=rng.randint(10,size=(3,4))
A

array([[6, 9, 2, 3],
       [0, 8, 6, 6],
       [0, 5, 6, 0]])

In [32]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-6, -1,  4,  3],
       [-6, -4,  4, -3]])

In [33]:
df = pd.DataFrame(A,columns = list('QRST'))
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -6 -1  4  3
2 -6 -4  4 -3

In [34]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -3  0 -7 -6
1 -8  0 -2 -2
2 -5  0  1 -5

In [35]:
halfrow = df.iloc[0,::2]

In [36]:
halfrow

Q    6
S    2
Name: 0, dtype: int32

In [37]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -6.0 NaN  4.0 NaN
2 -6.0 NaN  4.0 NaN

In [38]:
import pandas as pd
vals = np.array([1,None,3,4])
vals

array([1, None, 3, 4], dtype=object)

In [39]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [40]:
x= pd.Series(range(2),dtype=int)

In [41]:
x

0    0
1    1
dtype: int32

In [42]:
x[0]=None

In [43]:
x

0    NaN
1    1.0
dtype: float64

In [44]:
data = pd.Series([1,np.nan,'hello',None])

In [45]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [46]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [47]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [48]:
data.dropna()

0        1
2    hello
dtype: object

In [49]:
df=pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]])

In [50]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [51]:
df.isnull()

0      1      2
0  False   True  False
1  False  False  False
2   True  False  False

In [52]:
df.notnull()

0      1     2
0   True  False  True
1   True   True  True
2  False   True  True

In [53]:
df[df.notnull()]

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [54]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [55]:
df.dropna(axis = 'columns')

2
0  2
1  5
2  6

In [56]:
df[3]=np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [57]:
df.dropna(axis='columns',how = 'all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [58]:
df.dropna(axis='rows',thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [59]:
data = pd.Series([1,np.nan,2,None,3],index=list('abcde'))

In [60]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [61]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [62]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [63]:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [64]:
df.fillna(method='ffill',axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [65]:
#multiplyindexed series

In [66]:
index = [('california',2000),('california',2010),('New york',2000),('new york',2010),('texas',2000),('texas',2010)]
population = [3243242,23423432,23432423,34234,524332,342654654]
pop = pd.Series(population,index=index)

In [67]:
pop

(california, 2000)      3243242
(california, 2010)     23423432
(New york, 2000)       23432423
(new york, 2010)          34234
(texas, 2000)            524332
(texas, 2010)         342654654
dtype: int64

In [69]:
pop[('california',2010):('texas',2000)]

(california, 2010)    23423432
(New york, 2000)      23432423
(new york, 2010)         34234
(texas, 2000)           524332
dtype: int64

In [70]:
pop.index

Index([('california', 2000), ('california', 2010),   ('New york', 2000),
         ('new york', 2010),      ('texas', 2000),      ('texas', 2010)],
      dtype='object')

In [71]:
pop.index

('california', 2010)

In [72]:
index = pd.MultiIndex.from_tuples(index)

In [73]:
index

MultiIndex(levels=[['New york', 'california', 'new york', 'texas'], [2000, 2010]],
           labels=[[1, 1, 0, 2, 3, 3], [0, 1, 0, 1, 0, 1]])

In [74]:
pop.reindex(index)

california  2000      3243242
            2010     23423432
New york    2000     23432423
new york    2010        34234
texas       2000       524332
            2010    342654654
dtype: int64

In [75]:
pop

(california, 2000)      3243242
(california, 2010)     23423432
(New york, 2000)       23432423
(new york, 2010)          34234
(texas, 2000)            524332
(texas, 2010)         342654654
dtype: int64

In [76]:
pop = pop.reindex(index)

In [77]:
pop

california  2000      3243242
            2010     23423432
New york    2000     23432423
new york    2010        34234
texas       2000       524332
            2010    342654654
dtype: int64

In [78]:
pop[:,2010]

california     23423432
new york          34234
texas         342654654
dtype: int64

In [79]:
pop_df=pop.unstack()

In [80]:
pop_df

2000         2010
New york    23432423.0          NaN
california   3243242.0   23423432.0
new york           NaN      34234.0
texas         524332.0  342654654.0

In [81]:
pop_df.stack()

New york    2000     23432423.0
california  2000      3243242.0
            2010     23423432.0
new york    2010        34234.0
texas       2000       524332.0
            2010    342654654.0
dtype: float64

In [83]:
pop_df = pd.DataFrame({'total':pop,'under18':[235876657,96578465,6574653546,411,7643563,134342]})

In [84]:
pop_df

total     under18
california 2000    3243242   235876657
           2010   23423432    96578465
New york   2000   23432423  6574653546
new york   2010      34234         411
texas      2000     524332     7643563
           2010  342654654      134342

In [85]:
f_u18 = pop_df['under18']/pop_df['total']
f_u18.unstack()

2000      2010
New york    280.579330       NaN
california   72.728664  4.123156
new york           NaN  0.012006
texas        14.577716  0.000392

In [86]:
df = pd.DataFrame(np.random.rand(4,2),index = [['a','a','b','b'],[1,2,1,2]],columns =['data1','data2'])

In [87]:
df

data1     data2
a 1  0.361027  0.268157
  2  0.428474  0.202853
b 1  0.821090  0.310260
  2  0.034766  0.653958

In [88]:
data = {('california',2000):563465438,('california',2010):25720445704}
pd.Series(data)

california  2000      563465438
            2010    25720445704
dtype: int64

In [89]:
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [91]:
#herarchical indices and columns
index = pd.MultiIndex.from_product([[2017,2018],[1,2]],names=['a','b'])
columns = pd.MultiIndex.from_product([['nit','iit','gnit'],['study','hello']],names = ['college','best'])

In [92]:
data = np.round(np.random.randn(4,6),1)
data[:,::2]*=10
data +=37
study_data = pd.DataFrame(data,index = index,columns=columns)

In [93]:
study_data

college   nit         iit        gnit      
best    study hello study hello study hello
a    b                                     
2017 1   33.0  35.7  35.0  36.7   4.0  39.0
     2   24.0  37.0  48.0  35.2  25.0  35.3
2018 1   34.0  37.6  35.0  36.9  36.0  35.4
     2   48.0  38.2  33.0  37.0  49.0  37.8