warm up

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
r1= pd.Series(np.random.rand(10))

In [5]:
r2= pd.Series(np.random.rand(10))

In [6]:
dataframe = pd.DataFrame({'a':r2,'b':r1})

In [7]:
dataframe

a         b
0  0.812853  0.026982
1  0.479427  0.312410
2  0.512212  0.521096
3  0.642284  0.663736
4  0.166396  0.235573
5  0.297549  0.079802
6  0.703397  0.466990
7  0.923617  0.319054
8  0.171205  0.349047
9  0.069490  0.727917

In [8]:
dataframe.T

0         1         2         3         4         5         6  \
a  0.812853  0.479427  0.512212  0.642284  0.166396  0.297549  0.703397   
b  0.026982  0.312410  0.521096  0.663736  0.235573  0.079802  0.466990   

          7         8         9  
a  0.923617  0.171205  0.069490  
b  0.319054  0.349047  0.727917

In [9]:
dataframe.values

array([[ 0.8128527 ,  0.02698185],
       [ 0.47942727,  0.3124098 ],
       [ 0.51221237,  0.5210958 ],
       [ 0.6422842 ,  0.66373553],
       [ 0.16639598,  0.2355729 ],
       [ 0.29754906,  0.079802  ],
       [ 0.70339684,  0.46698964],
       [ 0.92361669,  0.3190538 ],
       [ 0.17120506,  0.34904722],
       [ 0.06948966,  0.72791728]])

In [10]:
dataframe['a']

0    0.812853
1    0.479427
2    0.512212
3    0.642284
4    0.166396
5    0.297549
6    0.703397
7    0.923617
8    0.171205
9    0.069490
Name: a, dtype: float64

In [12]:
dataframe.iloc[:3,:2]

a         b
0  0.812853  0.026982
1  0.479427  0.312410
2  0.512212  0.521096

In [17]:
dataframe.iloc[1]

a    0.479427
b    0.312410
Name: 1, dtype: float64

In [18]:
dataframe.loc[dataframe.a>.5]

a         b
0  0.812853  0.026982
2  0.512212  0.521096
3  0.642284  0.663736
6  0.703397  0.466990
7  0.923617  0.319054

In [20]:
dataframe[['a','b']]

a         b
0  0.812853  0.026982
1  0.479427  0.312410
2  0.512212  0.521096
3  0.642284  0.663736
4  0.166396  0.235573
5  0.297549  0.079802
6  0.703397  0.466990
7  0.923617  0.319054
8  0.171205  0.349047
9  0.069490  0.727917

In [21]:
rng = np.random.RandomState(23)
ser = pd.Series(rng.randint(0,10,4))
ser

0    3
1    6
2    8
3    9
dtype: int32

In [22]:
df=pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A','B','C','D'])

In [23]:
df

A  B  C  D
0  6  8  7  9
1  3  6  1  2
2  5  5  0  5

In [24]:
np.exp(df)

A            B            C            D
0  403.428793  2980.957987  1096.633158  8103.083928
1   20.085537   403.428793     2.718282     7.389056
2  148.413159   148.413159     1.000000   148.413159

In [25]:
np.sin(df*np.pi/4)

A             B         C         D
0 -1.000000 -2.449294e-16 -0.707107  0.707107
1  0.707107 -1.000000e+00  0.707107  1.000000
2 -0.707107 -7.071068e-01  0.000000 -0.707107

In [26]:
area = pd.Series({'alaska':123456,'texas':234567,'california':2354123},name = 'area')

In [27]:
area

alaska         123456
california    2354123
texas          234567
Name: area, dtype: int64

In [28]:
population = pd.Series({'california':235443252,'texas':234567891,'alaska':235234324})

In [29]:
population

alaska        235234324
california    235443252
texas         234567891
dtype: int64

In [30]:
population /area

alaska        1905.410219
california     100.013148
texas         1000.003798
dtype: float64

In [34]:
area.index | population.index

Index(['alaska', 'california', 'texas'], dtype='object')

In [35]:
A=pd.Series([2,4,6],index=[0,1,2])
B=pd.Series([1,3,5],index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [36]:
A.add(B,fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [37]:
A=pd.DataFrame(rng.randint(0,20,(2,2)),columns = list('ab'))
A

a   b
0  16   9
1  15  19

In [38]:
b=pd.DataFrame(rng.randint(0,10,(3,3)),columns = list('abc'))

In [39]:
b

a  b  c
0  1  7  4
1  1  1  4
2  6  7  3

In [43]:
A.add(b,fill_value=0)

a     b    c
0  17.0  16.0  4.0
1  16.0  20.0  4.0
2   6.0   7.0  3.0

In [44]:
A+b

a     b   c
0  17.0  16.0 NaN
1  16.0  20.0 NaN
2   NaN   NaN NaN

In [45]:
A=rng.randint(10,size=(3,4))
A

array([[6, 9, 2, 3],
       [0, 8, 6, 6],
       [0, 5, 6, 0]])

In [46]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-6, -1,  4,  3],
       [-6, -4,  4, -3]])

In [47]:
df = pd.DataFrame(A,columns = list('QRST'))
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -6 -1  4  3
2 -6 -4  4 -3

In [48]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -3  0 -7 -6
1 -8  0 -2 -2
2 -5  0  1 -5

In [49]:
halfrow = df.iloc[0,::2]

In [50]:
halfrow

Q    6
S    2
Name: 0, dtype: int32

In [51]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -6.0 NaN  4.0 NaN
2 -6.0 NaN  4.0 NaN

In [53]:
import pandas as pd
vals = np.array([1,None,3,4])
vals

array([1, None, 3, 4], dtype=object)

In [54]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [57]:
x= pd.Series(range(2),dtype=int)

In [58]:
x

0    0
1    1
dtype: int32

In [59]:
x[0]=None

In [60]:
x

0    NaN
1    1.0
dtype: float64

In [61]:
data = pd.Series([1,np.nan,'hello',None])

In [62]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [63]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [64]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [65]:
data.dropna()

0        1
2    hello
dtype: object

In [67]:
df=pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]])

In [68]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [69]:
df.isnull()

0      1      2
0  False   True  False
1  False  False  False
2   True  False  False

In [70]:
df.notnull()

0      1     2
0   True  False  True
1   True   True  True
2  False   True  True

In [71]:
df[df.notnull()]

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [72]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [73]:
df.dropna(axis = 'columns')

2
0  2
1  5
2  6

In [74]:
df[3]=np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [75]:
df.dropna(axis='columns',how = 'all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [76]:
df.dropna(axis='rows',thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [77]:
data = pd.Series([1,np.nan,2,None,3],index=list('abcde'))

In [78]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [80]:
data.fillna()

AttributeError: module 'pandas' has no attribute 'sum'