# what is object-oriented programming

<p>one good way of descibing something new is to compare it with something old.procedural programs look at world in terms of two entities,"data" and "function".in a procedural context ,the two entites are seperated from each other .a function takes data as input and return data as output.additionally,there's nothing customizable about a functiion with respect to data.As a result ,there are no barriers to using a function on various types of data,even inappropriately.<p>
    
<p>in the real world,however,we don't think of things or object as having these two features(data and function)as separate entities.that is real world objects are not(usually) merely data nor merely functions.real world objects instead have both 'state" and "behaviours"for instance,people have state(tall,short,etc.) and behaviour(playing cricket,running,etc),often both at the same time ,and of course in the same person<p>
    
<p>the aim of object oriented programming is to intimate this in terms of software,so that "objects " in software have two entities attached to them ,state and behaviour.<p>

<p> An object in programming is an entity or “variable”
that has two entities attached to it: data and things that act on that data.
The data are called attributes of the object, and the functions attached to the
object that can act on the data are called methods of the object. Importantly, Objects are
made up of
attributes and
methods.
you design these methods to act on the attributes; they aren’t random functions
someone has attached to the object. In contrast, in procedural programming,
variables have only one set of data, the value of the variable, with no
functions attached to the variable.<p>

<p> In the real world, objects are usually examples
or specific realizations of some class or type. For instance, individual
people are specific realizations of the class of human beings. The specific re- Object
instances are
specific
realizations of
a class.
alizations, or instances, differ from one another in details but have the same
pattern. For people, we all have the same general shape, organ structure, etc.
<b>In OOP, the specific realizations are called object instances, while the common
pattern is called a class</b>. In Python, this common pattern or template is
defined by the class statement.<p>

# how object work :strings

In [1]:
a='hello'

In [2]:
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [3]:
a.rstrip('lo')

'he'

In [4]:
a.upper()

'HELLO'

In [5]:
a.__doc__

"str(object='') -> str\nstr(bytes_or_buffer[, encoding[, errors]]) -> str\n\nCreate a new string object from the given object. If encoding or\nerrors is specified, then the object must expose a data buffer\nthat will be decoded using the given encoding and error handler.\nOtherwise, returns the result of object.__str__() (if defined)\nor repr(object).\nencoding defaults to sys.getdefaultencoding().\nerrors defaults to 'strict'."

In [6]:
a.__class__

str

In [7]:
a.title()

'Hello'

In [8]:
gn='the rain in greater noida'

In [9]:
b=gn.upper()

In [10]:
b.isupper()

True

In [11]:
b.count('N')

3

In [12]:
b

'THE RAIN IN GREATER NOIDA'

# how objects work:Arrays

In [13]:
import numpy as np


In [14]:
a=np.reshape(np.arange(12),(4,3))

In [15]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [16]:
a.__doc__

<p><ul>double underscore are more private</ul>
    <ul>single underscore are less private</ul>
    <ul>no underscore are public</ul></p>

In [17]:
a.astype('c')

array([[b'0', b'1', b'2'],
       [b'3', b'4', b'5'],
       [b'6', b'7', b'8'],
       [b'9', b'1', b'1']],
      dtype='|S1')

In [18]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
a.shape

(4, 3)

In [20]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [21]:
a.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [22]:
print (a.astype)

<built-in method astype of numpy.ndarray object at 0x0000000007B48800>


In [23]:
a=np.reshape(np.arange(12,dtype='f'),(3,4))

In [24]:
b=a.reshape(12)

In [25]:
b

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.], dtype=float32)

In [26]:
b.reshape(2,6)

array([[  0.,   1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.,  11.]], dtype=float32)

In [27]:
b.ravel()

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.], dtype=float32)

In [28]:
b.round(2)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.], dtype=float32)

# a class definition for a book class

In [29]:
class book(object):
    def __init__(self,authorlast,authorfirst,\
                title,place,publisher,year):
        self.authorlast=authorlast
        self.authorfirst=authorfirst
        self.title=title
        self.place=place
        self.publisher=publisher
        self.year=year
    def book_title(self):
        return self.title

In [30]:
get=book("krishnan","priyanshu","best machine learning application",\
    "greater noida","kaggle","2020")

In [31]:
get.book_title()

'best machine learning application'

In [32]:
class superbook(book):
    def millonsold(self):
        return "10 million book sold"

In [33]:
get_it=superbook("krishnan","priyanshu","best machine learning application",\
    "greater noida","kaggle","2020")

In [34]:
get_it.millionsold()

AttributeError: 'superbook' object has no attribute 'millionsold'

In [35]:
class dog(object):
    pass

In [36]:
dog()

In [37]:
class dog(object):
    def bark(self):
        print("wuff!")

In [38]:
dog()

In [39]:
dog()

In [40]:
dog().ru='15km/hr'

In [41]:
bila=dog()

In [42]:
bila.ru='15km/h'

In [43]:
bila.ru

'15km/h'

In [44]:
bila.ru='14km/h'

In [45]:
bila.ru

'14km/h'

In [46]:
class dataset(object):
    def __init__(self):
        self.data=None
    def store_data(self,raw_data):
        processed_data=raw_data**2
        self.data=processed_data
        return self.data

In [47]:
dataset.__init__

<function __main__.dataset.__init__>

In [48]:
dataset().data=15

In [49]:
print(dataset().data)

None


In [50]:
print(dataset().store_data(4))

16


In [51]:
dataset()

In [52]:
class dataset(object):
    def __init__(self,data=None):
        self.data=data
class mridataset(dataset):
    def __init__(self,data=None,parameters=None):
        super(mridataset,self).__init__(data)
        self.parameters=parameters
mri_data=mridataset(data=[1,23,4,5])

In [53]:
mri_data.data

[1, 23, 4, 5]

In [54]:
class my2vector(object):
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __add__(self,other):
        return my2vector(self.x+other.x,self.y+other.y)

In [55]:
v1=my2vector(1,3)
v2=my2vector(4,5)
v3=v1+v2

In [56]:
v1+v2

In [57]:
class my2vec(object):
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def get_x(self):
        return self.x
    def set_x(self,x):
        self.x=x
#     x=property(get_x,set_x)

In [58]:
v1=my2vec(2,3)

In [59]:
v1.get_x()

2

In [60]:
v1.set_x(4)

In [61]:
v1.get_x()

4

In [62]:
v1.x

4

In [63]:
v1.y

3

In [64]:
import random
class die(object):
    def __init__(self,sides=6):
        self._sides=sides
        self._value=None
        self.roll()
   
    def roll(self):
        self._value=1+random.randrange(self._sides)
        return self._value
    def __str__(self):
        return "die with %d sides,current value is %d"%(self._sides,self._value)
class winnerdie(die):
    def roll(self):
        super(winnerdie,self).roll()
        if self._value==6:
            return ("win",self._value)
        else:
            return ("loser",super(winnerdie,self).roll())

In [65]:
player=die()

In [66]:
player.roll()

4

In [67]:
x=winnerdie()

In [68]:
x.roll()

('loser', 1)

In [69]:
diep=die()

In [70]:
diep._sides

6

In [71]:
for _ in range(10):
    print (diep.roll())

4
4
6
5
6
4
6
3
6
5


In [72]:
print(diep)

die with 6 sides,current value is 5


In [73]:
winner_die = winnerdie()

In [74]:
for _ in range(10):
    print ( winner_die.roll())

('win', 6)
('loser', 6)
('loser', 5)
('loser', 6)
('loser', 6)
('loser', 5)
('loser', 3)
('loser', 3)
('loser', 6)
('loser', 2)


In [75]:
my_collection = ['a','b','c']
for _ in range(len(my_collection)):
    print (my_collection[_])

a
b
c


In [76]:
my_collection = {'a':1,'b':2,'c':3}

In [77]:
for _ in range(len(my_collection)):
    print(my_collection[_])

KeyError: 0

In [78]:
for _ in my_collection:
    print(my_collection[_])

1
2
3


In [79]:
class myiterable(object):
    def __init__(self,items):
        self.items=items
    def __iter__(self):
        return myiterator(self)
class myiterator(object):
    def __init__(self,my_iterable):
        self.my_iterable=my_iterable
        self.position=0
    def next(self):
        if self.position <len(self.my_iterable.items):
            value = self.my_iterable.items[self.position]
            self.position+=1
            return value
        else:
            raise StopIteration()
    def __iter__(self):
        return self

In [80]:
iterable=myiterable([1,2,3])

In [81]:
iterable.__iter__()

In [82]:
class beverage(object):
    def get_description(self):
        return "beverage"
    def get_cost(self):
        return 0.00
class coffee(beverage):
    def get_description(self):
        return "normal coffee"
    def get_cost(self):
        return 15.00
class tea(beverage):
    def get_description(self):
        return "tea"
    def get_cost(self):
        return 10.00

In [83]:
tea().get_cost()

10.0

In [84]:
class coffeewithlesssugar(coffee):
    def get_description(self):
        return super(coffewithlesssugar,self).get_description() + "with less sugar"
    def get_cost(self):
        return super(coffeewithlesssugar,self).get_cost()-2

In [85]:
coffeewithlesssugar().get_cost()

13.0

In [86]:
class bird(object):
    def __init__(self):
        self.wings=2
    def __str__(self):
        return 'awesome creature on planet earth'
    def sound(self):
        print('just smoothing')
    def display(self):
        print('looking beautiful')
    def take_off(self):
        print('bird starts flapping with wings')
    def fly_to(self,destination):
        print('now flying to %s'%destination)
    def land(self):
        print('slowing down ,extending legs,touch dowm')

In [87]:
chidiya=bird()

In [88]:
print(chidiya)

awesome creature on planet earth


In [89]:
class crow(bird):
    def display(self):
        print('looking ugly')

In [90]:
kaua=crow()

In [91]:
kaua.display()

looking ugly


In [92]:
# we need to change display and sound ever time 
# its annoying